uuid_file: "./uuid_container"
message:
  ms_memorize_received_message_id: 50000
  broadcast_address: "00000000000000000000000000000000"
  message_initial_id: 0
  meta:
    length_id: 32
    length_pid: 5
    length_frame: 252
    length_message_id: 3
    length_sequence_number: 8  # expected to be even length
rfm:
  timeout_receive: 20
  node: 255
  receive_timeout: 20
  receive_keep_listening: True
  send_keep_listening: True
  send_destination: 255
  send_node: 255
  identifier:
  identifiere
