uuid_file: "./uuid_container"
message_folder: "./storage/" # "~/tmp/lora"
message:
  ms_memorize_received_message_id: 50000
  broadcast_address: "00000000000000000000000000000000"
  message_initial_id: 0
  meta:
    length_id: "16"
    length_pid: "2"
    length_frame: "60"  # "100" # 252
    length_message_id: "1"
    length_sequence_number: "4"  # expected to be even length
rfm:
  timeout_receive: 20
  node: 255
  receive_timeout: 20
  receive_keep_listening: True
  send_keep_listening: True
  send_destination: 255
  send_node: 255
  identifier: 255